### ISSUE TITLE
python3

### ISSUE THREAD

**Issue by Vivisky** [moskytw/uniout#15]
i have learn python3 for one month,it seems pip3 cant install this,
$: sudo pip3 install uniout
it say:
Collecting uniout
  Using cached uniout-0.3.7.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-wia2didx/uniout/setup.py", line 6, in <module>
        import uniout
      File "/tmp/pip-build-wia2didx/uniout/uniout.py", line 9, in <module>
        if runs_in_ipython():
      File "/tmp/pip-build-wia2didx/uniout/_uniout.py", line 93, in runs_in_ipython
        import __builtin__
    ImportError: No module named '__builtin__'

**Comment by moskytw** [comment]
I think Python 3 doesn't need this module. :)

**Comment by Vivisky** [comment]
You are right, I finished my task with pickle(module), transform list to bytes, still thank you, but why do I see a LIU in your name(LIU=刘？,Do I think so much?）

**Comment by moskytw** [comment]
My ID is `moskytw`, and my name is _Mosky Liu_. _Liu_ is my last time, and is 劉 in traditional Chinese which is my native language. :)
